name: update-readme

on:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # Lascia il token default qui. Non serve forzare il PAT qui.
    
    - name: Estrai data e messaggio del commit
      run: |
        DATE=$(date +'%d %B %Y')
        MSG=$(git log -1 --pretty=%s)
        echo "**Ultimo aggiornamento:** $DATE – $MSG"
        sed -i '/^\*\*Ultimo aggiornamento:\*\*/c\**Ultimo aggiornamento:** '"$DATE – $MSG" README.md

    - name: Configura Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Commit e push con PAT
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git add README.md
        git commit -m "Aggiorna ultima data e messaggio nel README" || echo "Nessuna modifica da committare"
        git push https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git HEAD:main

