name: update-readme

on:
  push:
    branches: [ main ]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Estrai data e messaggio del commit
      id: vars
      run: |
        DATE=$(date +'%d %B %Y')
        MSG=$(git log -1 --pretty=%s)
        echo "LINE_REPLACE=**Ultimo aggiornamento:** $DATE – $MSG" >> "$GITHUB_ENV"

    - name: Sostituisci riga nel README
      run: |
        sed -i '/^\*\*Ultimo aggiornamento:\*\*/c\'"$LINE_REPLACE" README.md

    - name: Commit e push con PAT
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Aggiorna ultima data e messaggio nel README
        commit_user_name: Emipano
        commit_user_email: 195299999+Emipano@users.noreply.github.com
        github_token: ${{ secrets.PAT_TOKEN }}

