name: Aggiorna README con ultimo commit

on:
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Ottieni info ultimo commit
        id: commit_info
        run: |
          echo "date=$(git log -1 --format=%cd --date=short)" >> $GITHUB_OUTPUT
          echo "message=$(git log -1 --format=%s)" >> $GITHUB_OUTPUT

      - name: Aggiorna README.md
        run: |
          sed -i "s/^Ultimo aggiornamento:.*/Ultimo aggiornamento: ${{ steps.commit_info.outputs.date }} - ${{ steps.commit_info.outputs.message }}/" README.md

      - name: Commit e push modifiche
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: GitHub Actions
          committer_email: actions@github.com
          add: README.md
          message: 'Aggiorna data e messaggio ultimo commit nel README'
